version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    environment:
      - FLASK_ENV=development
      - JWT_SECRET=dev-only
      - CORS_ORIGINS=http://localhost:3000
    ports: ["5000:5000"]

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        REACT_APP_API_BASE: http://localhost:5000
    ports: ["3000:80"]
