name: backend-ci-cd

on:
  push:
    paths:
      - "week6/backend/**"
      - "week6/frontend/**"
      - "week6/docker/**"
      - ".github/workflows/backend-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # Setup Python for backend tests
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install & test backend
        working-directory: week5/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../week6/backend/requirements.txt
          pip install pytest pytest-cov
          pytest --maxfail=1 --disable-warnings --cov=../../Week3 --cov-report=xml

      # Login to Docker
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build backend image
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/week6-backend:latest week6/backend
          docker push ${{ secrets.DOCKER_USERNAME }}/week6-backend:latest

      # Build frontend image
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/week6-frontend:latest week6/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/week6-frontend:latest
