name: fullstack-ci-cd

on:
  push:
    paths:
      - "week6/backend/**"
      - "week6/frontend/**"
      - "week6/docker/**"
      - ".github/workflows/backend-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # ----------------------
      # Backend tests
      # ----------------------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install & test backend
        working-directory: week5/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../week6/backend/requirements.txt
          pip install pytest pytest-cov
          pytest -q --maxfail=1 --disable-warnings --cov=../../Week3 --cov-report=xml

      # ----------------------
      # Frontend tests
      # ----------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install & test frontend
        working-directory: week6/frontend
        run: |
          npm install
          npm test -- --watchAll=false

      # ----------------------
      # Docker login
      # ----------------------
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ----------------------
      # Build & push backend
      # ----------------------
      - name: Build & Push Backend
        working-directory: week6/backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/week6-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/week6-backend:latest

      # ----------------------
      # Build & push frontend
      # ----------------------
      - name: Build & Push Frontend
        working-directory: week6/frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/week6-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/week6-frontend:latest
